name: peanut
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.3
  dio: ^5.7.0
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  logger: ^2.5.0
  connectivity_plus: ^4.0.2
  shared_value: ^3.0.0
  intl: ^0.20.1
  easy_debounce: ^2.0.3
  shimmer: ^3.0.0
  flutter_dotenv: ^5.2.1
  flutter_spinkit:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/png/logo.png

